import type { Metadata } from "next";
import { SafeLink as Link } from "@/app/components/SafeLink";
import { ArticleHero, BackToApp, PageShell } from "@/app/components/PageShell";
import { links, releaseStatus } from "@/app/lib/site";

export const metadata: Metadata = { title: "DeltaTxt changelog", description: "Current DeltaTxt release and download information.", alternates: { canonical: "/apps/deltatxt/changelog" } };

export default function DeltaTxtChangelog() {
  return <PageShell><ArticleHero eyebrow="DeltaTxt / Changelog" title="DeltaTxt release notes." intro="Current version, download, and release information." />
    <article className="article-body wrap"><BackToApp href="/apps/deltatxt">Back to DeltaTxt</BackToApp><div className="release-entry"><div><span>Current Windows</span><time>2026</time></div><section><h2>DeltaTxt 0.3.2 for Windows</h2><p>This Windows-only update expands everyday editing and makes language-aware behavior more predictable. The Mac App Store edition remains at 0.3.1.</p><ul><li>Choose a document language manually or return to automatic extension detection; syntax highlighting, comments, autocomplete, indentation, and the function list follow the same choice.</li><li>Reorder tabs by dragging, use new tab file actions, and jump between matching braces with Ctrl+].</li><li>Use new line operations, case conversion, indentation, whitespace trimming, tab and space conversion, and file-path copy commands.</li><li>Enable optional trailing-whitespace removal on save.</li><li>Use the redesigned Find and Replace panel with clearer fields, live match counts, keyboard shortcuts, and actions for all open files.</li><li>Preserve LF, CRLF, or CR line endings when inserting and transforming lines.</li></ul><div className="inline-actions">{releaseStatus.deltaMacStoreReady ? <Link className="button button-primary" href={links.deltatxt.macStore}>Mac App Store</Link> : null}{releaseStatus.deltaDownloadReady ? <Link className="button button-secondary" href={links.deltatxt.download}>Windows 0.3.2 installer</Link> : <span className="button button-disabled">Windows installer pending verification</span>}{releaseStatus.deltaStoreReady ? <Link className="button button-secondary" href={links.deltatxt.store}>Microsoft Store</Link> : null}</div><p className="fine-print">Windows standalone installer size: approximately 70 MB.</p><p className="checksum"><strong>SHA-256</strong><code>2E7F8B561197C54E1072BF1D32C00D6C78D51C45EACBAE00BE26FAA23986C3B2</code></p></section></div><div className="release-entry"><div><span>Previous</span><time>2026</time></div><section><h2>DeltaTxt 0.3.1</h2><p>DeltaTxt 0.3.1 introduced the native Mac edition alongside the Windows editor, search, comparison, merge, and Python debugging workflows.</p></section></div></article>
  </PageShell>;
}
