import type { Metadata } from "next";
import { ArticleHero, BackToApp, PageShell } from "@/app/components/PageShell";

export const metadata: Metadata = { title: "WavePlume privacy policy", description: "How WavePlume handles recordings, transcripts, permissions, model downloads, and optional meeting summaries.", alternates: { canonical: "/apps/waveplume/privacy" } };

export default function WavePlumePrivacy() {
  return <PageShell accent="waveplume">
    <ArticleHero title="How WavePlume handles your data." intro="Effective September 22, 2026. This policy explains how WavePlume uses files, permissions, clipboard handoffs, optional summaries, and network access." />
    <article className="article-body wrap policy-copy">
      <BackToApp href="/apps/waveplume">Back to WavePlume</BackToApp>
      <h2>Local content</h2><p>WavePlume records selected screens or windows, system audio, and microphone audio, then creates transcripts on your device. It does not require an account and does not provide cloud storage for your meeting content.</p>
      <h2>No analytics or advertising</h2><p>The app does not include product analytics, behavioral advertising, or automatic upload of recordings, transcripts, or crash reports.</p>
      <h2>Model downloads</h2><p>When you choose a Whisper model, WavePlume may connect to Hugging Face to download model files. The Windows app uses Whisper.net’s model downloader; the Mac app uses WhisperKit’s Argmax repository. These requests download model data and do not upload your meeting audio, video, or transcript.</p>
      <h2>Optional meeting summaries on Mac</h2><p>The Mac app can summarize a meeting’s transcript when you ask it to, and you choose in Settings who writes the summary. Apple Intelligence writes it on your Mac and sends nothing. Ollama running on your Mac sends nothing off it; if you point WavePlume at Ollama on another computer, the transcript text goes to that computer, and the app asks first. Microsoft 365 Copilot is a hand-off: the app copies a request to your clipboard and opens Copilot, and you decide whether to send it. If you choose an online service such as Google Gemini, Groq, or another service that accepts the OpenAI chat-completions format, the app names the service, says how it may use what it receives, and asks your permission before sending. It then sends the text of that one transcript directly from your Mac to that service, using an API key from your own account, which the app keeps in your macOS keychain. Recordings and audio are never sent. ShrpWare does not receive these transcripts, summaries, or keys. The service you choose handles what it receives under its own terms and privacy policy; for example, Google states that content sent to the free tier of its Gemini API may be used to improve its products and may be read by human reviewers. Summaries are saved beside the transcript on your Mac.</p>
      <h2>Email on Mac</h2><p>The Mac app can open a new message in Mail or Outlook with a summary in it or a transcript attached. It never sends email itself; you address and send the message.</p>
      <h2>Optional Webex schedule connection</h2><p>If you choose to connect Webex calendar schedule information, WavePlume uses that connection to show relevant meeting schedule details. The feature is optional and does not change where recording or transcription happens. The Mac app does not currently include a calendar or Webex connection.</p>
      <h2>Sending a transcript to another app</h2><p>On Windows, Send to… copies the transcript and the prompt you choose to the Windows clipboard, then opens the chat assistant you selected in your browser. WavePlume does not paste or upload the transcript. You decide whether to share it after reviewing the destination. If you choose to send the transcript as a file, WavePlume creates a temporary copy under <code>%TEMP%\WavePlume\handoff</code>. The copy remains for seven days so a later paste can work, and older copies are removed the next time you use the feature.</p>
      <h2>Permissions</h2><p>Depending on your operating system and the features you use, WavePlume may request access to screen/system audio capture, microphone input, files and folders, calendar schedule information, notifications for recording countdowns, the local network when you enter a summary server on another computer, and the network for model downloads and summaries you ask for.</p>
      <h2>Collection and sharing</h2><p>ShrpWare does not collect, sell, or share your recordings, transcripts, or app usage through WavePlume. Files you place in a third-party synced folder are subject to that provider’s terms. A transcript you choose to paste into a browser or another app, or ask the Mac app to send to a summary service, is governed by that destination’s terms. Because a transcript you send for an online summary leaves your device and may be kept by that service, the Mac App Store listing declares it as user content collected for app functionality, not linked to you and not used for tracking.</p>
      <h2>Your responsibility when recording</h2><p>You are responsible for complying with applicable recording-consent laws, workplace rules, and meeting policies.</p>
      <h2>Questions and changes</h2><p>Questions can be sent to <a href="mailto:support@shrpware.com">support@shrpware.com</a>. Material policy changes will be posted on this page with a new effective date.</p>
    </article>
  </PageShell>;
}
