import type { Metadata } from "next";
import { ArticleHero, BackToApp, PageShell } from "@/app/components/PageShell";

export const metadata: Metadata = { title: "WavePlume privacy policy", description: "How WavePlume handles recordings, transcripts, permissions, model downloads, and optional meeting summaries.", alternates: { canonical: "/apps/waveplume/privacy" } };

export default function WavePlumePrivacy() {
  return <PageShell accent="waveplume">
    <ArticleHero title="How WavePlume handles your data." intro="Effective September 23, 2026. This policy explains how WavePlume uses files, permissions, clipboard handoffs, optional summaries, and network access." />
    <article className="article-body wrap policy-copy">
      <BackToApp href="/apps/waveplume">Back to WavePlume</BackToApp>
      <h2>Local content</h2><p>WavePlume records selected screens or windows, system audio, and microphone audio, then creates transcripts on your device. It does not require an account and does not provide cloud storage for your meeting content.</p>
      <h2>No analytics or advertising</h2><p>The app does not include product analytics, behavioral advertising, or automatic upload of recordings, transcripts, or crash reports.</p>
      <h2>Model downloads</h2><p>When you choose a Whisper model, WavePlume may connect to Hugging Face to download model files. The Windows app uses Whisper.net’s model downloader. The Mac app uses WhisperKit, which downloads Argmax’s WhisperKit model files and, from a second Hugging Face repository, OpenAI’s matching Whisper tokenizer files. The Mac app also downloads WavePlume’s internal summary model, a model made by Google DeepMind, from Hugging Face, once, and only after you agree. These requests download model data and do not upload your meeting audio, video, or transcript.</p>
      <h2>Optional meeting summaries on Mac</h2><p>The Mac app can summarize a meeting’s transcript when you ask it to, and you choose in Settings who writes the summary. By default WavePlume’s internal model writes it on your Mac, even offline, and sends nothing. Apple Intelligence also writes it on your Mac and sends nothing. Microsoft 365 Copilot, Claude, and ChatGPT are hand-offs: the app copies a request containing the transcript’s text, with the meeting’s name and length, to your clipboard and opens the one you chose (see “Sending a transcript to another app” below), and you decide whether to send it there, from your own account, where that service’s terms and your account settings apply. If you choose an online service such as Google Gemini, Groq, or another service that accepts the OpenAI chat-completions format, the app names the service, says how it may use what it receives, and asks your permission before sending, each time unless you tick “Don’t ask again” for that service. It then sends the text of that one transcript, with the meeting’s name and length, directly from your Mac to that service, using an API key from your own account, which the app keeps in your macOS keychain. Recordings and audio are never sent. If the service you enter is a model server running on your own Mac, the text stays on your Mac and the app does not ask. A server on another computer counts as leaving your Mac, so the app asks first. On your own network such a server can be reached over plain http, which is not encrypted, so the transcript and any API key would travel unencrypted; use an https address if the network is shared. A server anywhere else has to use https. ShrpWare does not receive these transcripts, summaries, or keys. The service you choose handles what it receives under its own terms and privacy policy; for example, Google states that content sent to the free tier of its Gemini API may be used to improve its products and may be read by human reviewers. Summaries are saved beside the transcript on your Mac.</p>
      <h2>Email on Mac</h2><p>The Mac app can open a new message with a summary in it or a transcript attached. In Mail, the summary goes into the draft or the transcript is attached to it. In Outlook, the app opens an addressed, titled message and puts the summary, or the transcript file, on your clipboard for you to paste in; other apps on your Mac can read the clipboard until you copy something else. The app never sends email itself; you address and send the message. To attach a transcript, it keeps a temporary copy in the app’s temporary folder until macOS clears that folder, and it stores on your Mac the email addresses you enter in Settings.</p>
      <h2>Optional Webex schedule connection</h2><p>If you choose to connect Webex calendar schedule information, WavePlume uses that connection to show relevant meeting schedule details. The feature is optional and does not change where recording or transcription happens. The Mac app does not currently include a calendar or Webex connection.</p>
      <h2>Sending a transcript to another app</h2><p>On Windows, Send to… copies the transcript and the prompt you choose to the Windows clipboard, then opens the chat assistant you selected in your browser. WavePlume does not paste or upload the transcript. You decide whether to share it after reviewing the destination. If you choose to send the transcript as a file, WavePlume creates a temporary copy under <code>%TEMP%\WavePlume\handoff</code>. The copy remains for seven days so a later paste can work, and older copies are removed the next time you use the feature.</p>
      <p>On Mac, the Microsoft 365 Copilot, Claude, and ChatGPT summary hand-offs put the request on your clipboard, and the request contains the transcript’s text, with the meeting’s name and length. Other apps on your Mac, including clipboard managers, can read the clipboard, and macOS may offer it to your other Apple devices through Universal Clipboard, until you copy something else. For a transcript too long to paste, the copied request leaves the transcript out, and the app shows its transcript file in Finder for you to drag into the chat instead. The app reads the clipboard only when you choose to paste the assistant’s reply back into the summary. WavePlume does not send the request itself; you decide whether to paste and send it.</p>
      <h2>Recognizing a meeting on Mac</h2><p>While the Mac app is open and Screen &amp; System Audio Recording is on for it, WavePlume reads the titles of open windows, and which apps are playing sound, every few seconds, to recognize a Microsoft Teams, Zoom, or Webex call, to offer to record it, and to keep other windows out of the picture while a call is on the screen you record. This happens only on your Mac and nothing from it is sent. It is held in memory and shown in the app’s activity log while the app runs; the only thing kept is the call’s name, and only when it is used to name a recording you did not name. Start by itself and Automatically pause during quiet breaks are off unless you turn them on. If you turn either on, the app listens to your Mac’s system sound and to the microphone you selected, only to measure the level, while it waits for a meeting to begin or for a break to end; if a microphone is selected, the macOS microphone indicator shows while it listens. Nothing is recorded, saved, or sent while the app only listens.</p>
      <h2>Permissions</h2><p>Depending on your operating system and the features you use, WavePlume may request access to screen/system audio capture, microphone input, files and folders, notifications for recording countdowns, the local network when you enter a summary server on another computer, and the network for model downloads and summaries you ask for. On Windows it may also request access to calendar schedule information, if you connect Webex as described above. The Mac app requests no calendar access. On Mac, Screen &amp; System Audio Recording is used to list and capture the display, application, or window you select and its internal audio, and to recognize a call as described above; the microphone is used to include the input device you select, to show its level, and, if you turn on Start by itself or Automatically pause during quiet breaks, to measure its level while the app waits.</p>
      <h2>Keeping and deleting your data</h2>
      <p>WavePlume keeps recordings, transcripts, and summaries in the Recording Library folder on your own computer, apart from the temporary copies described above and any copy you save or send yourself, and keeps nothing about them on any server of ours. On Mac, the library is the folder you choose; in the App Store version it defaults to a folder inside the app’s sandboxed container. The settings you enter, such as email addresses and a summary server address, stay on your Mac. To delete a meeting on Mac, use Move to Trash in the library or move its folder to the Trash in Finder; the recording, transcript, and summary go with it. On Windows, session folders in your recording library are ordinary folders you can open and delete in Explorer.</p>
      <p>On Mac, Settings can delete downloaded transcription models and remove the summary model, and Remove Key under Summaries in Settings removes an API key from your keychain (you can also remove it in Keychain Access).</p>
      <p>You can change microphone and screen recording access for WavePlume at any time in your operating system’s privacy settings, which on Mac is Privacy &amp; Security in System Settings. A transcript you sent to an online summary service, or pasted into a chat assistant, is held by that service under its own terms, so ask that service if you want it deleted; ShrpWare holds no copy.</p>
      <h2>Collection and sharing</h2><p>ShrpWare does not collect, sell, or share your recordings, transcripts, or app usage through WavePlume. Files you place in a third-party synced folder are subject to that provider’s terms. A transcript you choose to paste into a browser or another app, or ask the Mac app to send to a summary service, is governed by that destination’s terms. Because a transcript you send for an online summary leaves your device and may be kept by that service, the Mac App Store listing declares it as user content collected for app functionality, not linked to you and not used for tracking.</p>
      <h2>Your responsibility when recording</h2><p>You are responsible for complying with applicable recording-consent laws, workplace rules, and meeting policies.</p>
      <h2>Questions and changes</h2><p>Questions can be sent to <a href="mailto:support@shrpware.com">support@shrpware.com</a>. Material policy changes will be posted on this page with a new effective date.</p>
    </article>
  </PageShell>;
}
